# The URL the site will be built for
base_url = "https://bilfri.by.lukaskluge.dk"

title = "Bilfri By"

# a description; you can use markdown here if you like
description="Fordi cykelstier gi'r mer' mening end motorveje"
default_language = "en"

highlight_theme = "solarized-light"
generate_feed = true
feed_limit = 20

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# theme options
profile = "bilfri-by-logo-no-text-white-background.svg" # the name of the profile picture in static/img/
color_themes = ["light", "dark"]
country_flags = true # Display languages as country flags. Defaults to false.
author = "Lukas Kluge"

[[extra.socials]]
icon = "facebook"
display = "Facebook"
uri = "https://facebook.com/bilfri.by"

[[extra.socials]]
icon = "instagram"
display = "Instagram"
uri = "https://instagram.com/bilfri.by"

[extra.font_awesome]
kit = "e307e34624"
