# The URL the site will be built for
base_url = "https://delicate-profiterole-399703.netlify.app"

title = "Bilfri By"
# a description; you can use markdown here if you like
description="Bilfri By er en fælles cykeltur for alle der synes cykelstier giver mere mening end motorveje"
default_language = "da"

highlight_theme = "solarized-light"
generate_feed = true
feed_limit = 20

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
# theme options
profile = "bilfri-by-logo-v1.1-hvid-baggrund.svg" # the name of the profile picture in static/img/
color_themes = ["default", "dark"]
country_flags = true # Display languages as country flags. Defaults to false.

[[extra.socials]]
icon = "facebook"
display = "Bilfri By on Facebook"
uri = "https://facebook.com/CriticalMassCPH"

[[extra.socials]]
icon = "instagram"
display = "Bilfri By on Instagram"
uri = "https://instagram.com/bilfri.by"

[[extra.socials]]
icon = "envelope"
icon_class = "fas"
display = "say hello"
uri = "mailto:github@andrewplaza.dev?subject=hi"

[extra.comments] # Optional
repo = "insipx/Ergo"
theme = "github-light"
label = "comment" # Optional
#issue_number = 1 # Specify either this or term
term = "pathname"

[extra.font_awesome]
kit = "e307e34624"
